import type { BayesNodeData } from './modelIr.js';

export type StructureBlockTypeId = NonNullable<BayesNodeData['blockTypeId']>;

export interface StructureBlockPaletteItem {
  blockTypeId: StructureBlockTypeId;
  label: string;
  note: string;
}

export const STRUCTURE_BLOCK_PALETTE: StructureBlockPaletteItem[] = [
  { blockTypeId: 'gp_regression', label: 'Gaussian process', note: '座標に沿う相関' },
  { blockTypeId: 'state_space', label: 'State space', note: '連続状態の時間発展' },
  { blockTypeId: 'hidden_markov', label: 'Hidden Markov', note: '離散状態の遷移' },
  { blockTypeId: 'mixture', label: 'Mixture', note: '複数の生成成分' },
];

export const ADVANCED_STRUCTURE_BLOCK_PALETTE: StructureBlockPaletteItem[] = [
  { blockTypeId: 'survival', label: 'Survival', note: 'hazardと打ち切り' },
  { blockTypeId: 'competing_risks', label: 'Competing risks', note: '原因別hazard' },
  { blockTypeId: 'spatial_gmrf', label: 'Spatial CAR / GMRF', note: '隣接する空間効果' },
  { blockTypeId: 'differential_process', label: 'ODE / SDE', note: '微分方程式の状態' },
  { blockTypeId: 'copula', label: 'Copula', note: '周辺分布間の依存' },
];

export const BLOCK_PRESETS: Record<StructureBlockTypeId, BayesNodeData> = {
  gp_regression: {
    kind: 'model_block',
    name: 'f_gp[i]',
    shape: ['N'],
    plate: 'obs',
    expression: 'f_gp = GP(coordinates; kernel)',
    blockTypeId: 'gp_regression',
    blockInputs: { coordinates: 'x[i]', kernel: 'RBF(ell, rho)' },
    blockOutputPort: 'latent_function',
    blockConfig: { approximation: 'exact' },
    validationLevel: 'structured',
    notes: 'Kernel family and approximation choice remain explicit for implementation.',
  },
  gam_smooth: {
    kind: 'model_block',
    name: 'f_smooth[i]',
    shape: ['N'],
    plate: 'obs',
    expression: 'f_smooth = basis(x) @ coefficients',
    blockTypeId: 'gam_smooth',
    blockInputs: { predictor: 'x[i]', basis: 'B(x) @ beta_smooth' },
    blockOutputPort: 'smooth_effect',
    blockConfig: { basis_family: 'spline', basis_count: 10 },
    validationLevel: 'structured',
  },
  mixture: {
    kind: 'model_block',
    name: 'mixture_value[i]',
    shape: ['N'],
    plate: 'obs',
    expression: 'mixture_value ~ Mixture(weights, components)',
    blockTypeId: 'mixture',
    blockInputs: { weights: 'weights', components: 'components' },
    blockOutputPort: 'mixture_value',
    blockConfig: { component_count: 2, marginalize_assignments: true },
    validationLevel: 'structured',
  },
  state_space: {
    kind: 'model_block',
    name: 'state[t]',
    shape: ['T'],
    plate: 'time',
    expression: 'state[t] = transition(state[t-1]) + innovation[t]',
    blockTypeId: 'state_space',
    blockInputs: { initial_state: 'state[1]', transition: 'transition(state[t-1])', innovation: 'sigma_state' },
    blockOutputPort: 'state',
    blockConfig: { transition_family: 'linear_gaussian', time_axis: 'time' },
    validationLevel: 'structured',
  },
  hidden_markov: {
    kind: 'model_block',
    name: 'state[t]',
    shape: ['T'],
    plate: 'time',
    expression: 'state[t] ~ Categorical(transition_matrix[state[t-1]])',
    blockTypeId: 'hidden_markov',
    blockInputs: { initial_probs: 'initial_probs', transition_matrix: 'transition_matrix', emission: 'emission[state[t]]' },
    blockOutputPort: 'state_sequence',
    blockConfig: { state_count: 2, marginalize_states: true },
    validationLevel: 'structured',
  },
  survival: {
    kind: 'model_block',
    name: 'survival_loglik[i]',
    shape: ['N'],
    plate: 'obs',
    expression: 'event[i] * log(hazard(time[i])) - cumulative_hazard(time[i])',
    blockTypeId: 'survival',
    blockInputs: {
      time: 'time[i]',
      event: 'event[i]',
      interval_lower: 'time_lower[i]',
      interval_upper: 'time_upper[i]',
      hazard: 'hazard(time[i])',
      cumulative_hazard: 'cumulative_hazard(time[i])',
    },
    blockOutputPort: 'log_likelihood',
    blockConfig: {
      likelihood_family: 'hazard',
      censoring: 'right',
      time_axis: 'obs',
    },
    validationLevel: 'structured',
    notes: 'Event indicator and censoring rule are kept separate from the hazard definition.',
  },
  competing_risks: {
    kind: 'model_block',
    name: 'cause_loglik[i]',
    shape: ['N'],
    plate: 'obs',
    expression: 'log(cause_hazard[cause[i]](time[i])) - cumulative_hazard_all(time[i])',
    blockTypeId: 'competing_risks',
    blockInputs: {
      time: 'time[i]',
      event: 'event[i]',
      cause: 'cause[i]',
      interval_lower: 'time_lower[i]',
      interval_upper: 'time_upper[i]',
      cause_hazards: 'cause_hazards(time[i])',
      cumulative_hazard: 'cumulative_hazard_all(time[i])',
    },
    blockOutputPort: 'cause_log_likelihood',
    blockConfig: {
      risk_count: 2,
      censoring: 'right',
      time_axis: 'obs',
    },
    validationLevel: 'structured',
    notes: 'Cause-specific hazards and all-cause cumulative hazard remain explicit.',
  },
  spatial_gmrf: {
    kind: 'model_block',
    name: 'spatial_effect[s]',
    shape: ['S'],
    plate: 'spatial',
    expression: 'spatial_effect ~ GMRF(adjacency, precision)',
    blockTypeId: 'spatial_gmrf',
    blockInputs: {
      adjacency: 'adjacency',
      spatial_index: 'spatial_id[i]',
      precision: 'tau_spatial',
    },
    blockOutputPort: 'spatial_effect',
    blockConfig: {
      family: 'CAR',
      intrinsic: true,
      constraint: 'sum_to_zero',
      spatial_axis: 's',
    },
    validationLevel: 'structured',
    notes: 'Adjacency, spatial index, intrinsic rank deficiency, and identification constraint are explicit.',
  },
  differential_process: {
    kind: 'model_block',
    name: 'state[t]',
    shape: ['T'],
    plate: 'time',
    expression: 'd(state)/dt = dynamics(state, parameters, time)',
    blockTypeId: 'differential_process',
    blockInputs: {
      initial_state: 'state_initial',
      dynamics: 'dynamics(state, parameters, time)',
      parameters: 'theta_dynamics',
      time: 'time[t]',
      observation_model: 'observation(state[t])',
    },
    blockOutputPort: 'trajectory',
    blockConfig: {
      equation_type: 'ODE',
      solver: 'rk45',
      relative_tolerance: '1e-5',
      absolute_tolerance: '1e-6',
    },
    validationLevel: 'structured',
    notes: 'Equation type, solver, tolerances, and observation model are implementation contract fields.',
  },
  copula: {
    kind: 'model_block',
    name: 'joint_value[i]',
    shape: ['N'],
    plate: 'obs',
    expression: 'joint_value = Copula(marginals, dependence)',
    blockTypeId: 'copula',
    blockInputs: {
      marginals: 'marginal_cdfs',
      uniforms: 'u[i]',
      dependence: 'correlation',
    },
    blockOutputPort: 'joint_value',
    blockConfig: {
      family: 'gaussian',
      dimension: 2,
      jacobian_owner: 'backend',
    },
    validationLevel: 'structured',
    notes: 'Marginal transforms, dependence parameters, and Jacobian ownership remain separate.',
  },
};
